//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pos.Infrastructure.EntityFramework.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetails
    {
        public OrderDetails()
        {
            this.Products = new HashSet<Products>();
        }
    
        public int Id { get; set; }
        public int Quantity { get; set; }
        public int OrderId { get; set; }
    
        public virtual Orders Orders { get; set; }
        public virtual ICollection<Products> Products { get; set; }
    }
}
