//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pos.Infrastructure.EntityFramework.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Id { get; set; }
        public string ProductCode { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public System.DateTime DistributedDate { get; set; }
        public int ProductTypeId { get; set; }
        public int OrderDetailId { get; set; }
    
        public virtual OrderDetail OrderDetail { get; set; }
        public virtual ProductType ProductType { get; set; }
    }
}
